### ISSUE TITLE
Spiral\Scheduler\Job\Job::filtersPass(): Argument #1 ($container) must be of type Spiral\Core\Container

### ISSUE THREAD

**Issue by algirdasci** [spiral-packages/scheduler#21]
When trying to run `schedule:run` command, TypeError occurs:

```
TypeError: Spiral\Scheduler\Job\Job::filtersPass(): Argument #1 ($container) must be of type Spiral\Core\Container, Psr\Container\ContainerInterface SCOPED PROXY given, called in /app/vendor/spiral-packages/scheduler/src/Commands/ScheduleRunCommand.php on line 28 in /app/vendor/spiral-packages/scheduler/src/Job/Job.php at line 292
```

Would it be logical to change `Spiral\Scheduler\Job` file and use `Psr\Container\ContainerInterface` instead of `Spiral\Core\Container`?

**Comment by roxblnfk** [comment]
I think Yes

**Comment by Filipponik** [comment]
I have the same problem

When will the pull request be merged? My scheduler just doesn't work because of this. Or are there any workarounds to fix this right now?
